/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsCorrosionRouteImport } from './routes/models.corrosion'
import { Route as ModelsCorrosionPipelineInspection01RouteImport } from './routes/models.corrosion_.pipeline-inspection-01'
import { Route as ModelsCorrosionProjectIdRouteImport } from './routes/models.corrosion_.$projectId'
import { Route as ModelsCorrosionNewRouteImport } from './routes/models.corrosion.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsCorrosionRoute = ModelsCorrosionRouteImport.update({
  id: '/models/corrosion',
  path: '/models/corrosion',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsCorrosionPipelineInspection01Route =
  ModelsCorrosionPipelineInspection01RouteImport.update({
    id: '/models/corrosion_/pipeline-inspection-01',
    path: '/models/corrosion/pipeline-inspection-01',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelsCorrosionProjectIdRoute =
  ModelsCorrosionProjectIdRouteImport.update({
    id: '/models/corrosion_/$projectId',
    path: '/models/corrosion/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelsCorrosionNewRoute = ModelsCorrosionNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ModelsCorrosionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/models/corrosion': typeof ModelsCorrosionRouteWithChildren
  '/models/corrosion/new': typeof ModelsCorrosionNewRoute
  '/models/corrosion/pipeline-inspection-01': typeof ModelsCorrosionPipelineInspection01Route
  '/models/corrosion/$projectId': typeof ModelsCorrosionProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/models/corrosion': typeof ModelsCorrosionRouteWithChildren
  '/models/corrosion/new': typeof ModelsCorrosionNewRoute
  '/models/corrosion/pipeline-inspection-01': typeof ModelsCorrosionPipelineInspection01Route
  '/models/corrosion/$projectId': typeof ModelsCorrosionProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/models/corrosion': typeof ModelsCorrosionRouteWithChildren
  '/models/corrosion/new': typeof ModelsCorrosionNewRoute
  '/models/corrosion_/pipeline-inspection-01': typeof ModelsCorrosionPipelineInspection01Route
  '/models/corrosion_/$projectId': typeof ModelsCorrosionProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/models/corrosion'
    | '/models/corrosion/new'
    | '/models/corrosion/pipeline-inspection-01'
    | '/models/corrosion/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/models/corrosion'
    | '/models/corrosion/new'
    | '/models/corrosion/pipeline-inspection-01'
    | '/models/corrosion/$projectId'
  id:
    | '__root__'
    | '/'
    | '/models/corrosion'
    | '/models/corrosion/new'
    | '/models/corrosion_/pipeline-inspection-01'
    | '/models/corrosion_/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelsCorrosionRoute: typeof ModelsCorrosionRouteWithChildren
  ModelsCorrosionPipelineInspection01Route: typeof ModelsCorrosionPipelineInspection01Route
  ModelsCorrosionProjectIdRoute: typeof ModelsCorrosionProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/corrosion': {
      id: '/models/corrosion'
      path: '/models/corrosion'
      fullPath: '/models/corrosion'
      preLoaderRoute: typeof ModelsCorrosionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/corrosion_/pipeline-inspection-01': {
      id: '/models/corrosion_/pipeline-inspection-01'
      path: '/models/corrosion/pipeline-inspection-01'
      fullPath: '/models/corrosion/pipeline-inspection-01'
      preLoaderRoute: typeof ModelsCorrosionPipelineInspection01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/corrosion_/$projectId': {
      id: '/models/corrosion_/$projectId'
      path: '/models/corrosion/$projectId'
      fullPath: '/models/corrosion/$projectId'
      preLoaderRoute: typeof ModelsCorrosionProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/corrosion/new': {
      id: '/models/corrosion/new'
      path: '/new'
      fullPath: '/models/corrosion/new'
      preLoaderRoute: typeof ModelsCorrosionNewRouteImport
      parentRoute: typeof ModelsCorrosionRoute
    }
  }
}

interface ModelsCorrosionRouteChildren {
  ModelsCorrosionNewRoute: typeof ModelsCorrosionNewRoute
}

const ModelsCorrosionRouteChildren: ModelsCorrosionRouteChildren = {
  ModelsCorrosionNewRoute: ModelsCorrosionNewRoute,
}

const ModelsCorrosionRouteWithChildren = ModelsCorrosionRoute._addFileChildren(
  ModelsCorrosionRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelsCorrosionRoute: ModelsCorrosionRouteWithChildren,
  ModelsCorrosionPipelineInspection01Route:
    ModelsCorrosionPipelineInspection01Route,
  ModelsCorrosionProjectIdRoute: ModelsCorrosionProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
