/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelsCorrosionRouteImport } from './routes/models.corrosion'
import { Route as ModelsCorrosionPipelineInspection01RouteImport } from './routes/models.corrosion_.pipeline-inspection-01'
import { Route as ModelsCorrosionProjectIdRouteImport } from './routes/models.corrosion_.$projectId'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsCorrosionRoute = ModelsCorrosionRouteImport.update({
  id: '/models/corrosion',
  path: '/models/corrosion',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsCorrosionPipelineInspection01Route =
  ModelsCorrosionPipelineInspection01RouteImport.update({
    id: '/models/corrosion_/pipeline-inspection-01',
    path: '/models/corrosion/pipeline-inspection-01',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModelsCorrosionProjectIdRoute =
  ModelsCorrosionProjectIdRouteImport.update({
    id: '/models/corrosion_/$projectId',
    path: '/models/corrosion/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/models/corrosion': typeof ModelsCorrosionRoute
  '/models/corrosion/$projectId': typeof ModelsCorrosionProjectIdRoute
  '/models/corrosion/pipeline-inspection-01': typeof ModelsCorrosionPipelineInspection01Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/models/corrosion': typeof ModelsCorrosionRoute
  '/models/corrosion/$projectId': typeof ModelsCorrosionProjectIdRoute
  '/models/corrosion/pipeline-inspection-01': typeof ModelsCorrosionPipelineInspection01Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/team': typeof TeamRoute
  '/models/corrosion': typeof ModelsCorrosionRoute
  '/models/corrosion_/$projectId': typeof ModelsCorrosionProjectIdRoute
  '/models/corrosion_/pipeline-inspection-01': typeof ModelsCorrosionPipelineInspection01Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/team'
    | '/models/corrosion'
    | '/models/corrosion/$projectId'
    | '/models/corrosion/pipeline-inspection-01'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/team'
    | '/models/corrosion'
    | '/models/corrosion/$projectId'
    | '/models/corrosion/pipeline-inspection-01'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/team'
    | '/models/corrosion'
    | '/models/corrosion_/$projectId'
    | '/models/corrosion_/pipeline-inspection-01'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  TeamRoute: typeof TeamRoute
  ModelsCorrosionRoute: typeof ModelsCorrosionRoute
  ModelsCorrosionProjectIdRoute: typeof ModelsCorrosionProjectIdRoute
  ModelsCorrosionPipelineInspection01Route: typeof ModelsCorrosionPipelineInspection01Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/corrosion': {
      id: '/models/corrosion'
      path: '/models/corrosion'
      fullPath: '/models/corrosion'
      preLoaderRoute: typeof ModelsCorrosionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/corrosion_/pipeline-inspection-01': {
      id: '/models/corrosion_/pipeline-inspection-01'
      path: '/models/corrosion/pipeline-inspection-01'
      fullPath: '/models/corrosion/pipeline-inspection-01'
      preLoaderRoute: typeof ModelsCorrosionPipelineInspection01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/corrosion_/$projectId': {
      id: '/models/corrosion_/$projectId'
      path: '/models/corrosion/$projectId'
      fullPath: '/models/corrosion/$projectId'
      preLoaderRoute: typeof ModelsCorrosionProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  TeamRoute: TeamRoute,
  ModelsCorrosionRoute: ModelsCorrosionRoute,
  ModelsCorrosionProjectIdRoute: ModelsCorrosionProjectIdRoute,
  ModelsCorrosionPipelineInspection01Route:
    ModelsCorrosionPipelineInspection01Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
